package charistas.actibit;

import android.app.AlertDialog;
import android.app.Dialog;
import android.app.DialogFragment;
import android.content.Context;
import android.content.DialogInterface;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.EditText;

/**
 * This class is responsible for initializing and configuring the distance input field.
 */
public class SetDistanceDialogFragment extends DialogFragment {

    /**
     * Create a new instance of this fragment.
     * @return A new instance of this fragment
     */
    static SetDistanceDialogFragment createFragment() {
        return new SetDistanceDialogFragment();
    }

    /**
     * Responsible for initializing and configuring the dialog that lets the user set the total
     * hours and minutes spent on the chosen Fitbit activity.
     * @param savedInstanceState The state generated by a previous instance of this activity
     * @return The newly created dialog
     */
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
        LayoutInflater inflater = getActivity().getLayoutInflater();
        View view = inflater.inflate(R.layout.fragment_distance_dialog, null);

        builder.setTitle(getString(R.string.set_distance));
        final EditText distance = (EditText)view.findViewById(R.id.distanceEditText);
        builder.setView(view);

        // Configure the OK and Cancel buttons of the dialog
        builder.setPositiveButton(getString(R.string.OK), new DialogInterface.OnClickListener() {
            public void onClick(DialogInterface dialog, int id) {
                String chosenDistance = distance.getText().toString();
                distanceListener.onDone(chosenDistance);
            }
        });
        builder.setNegativeButton(getString(R.string.cancel), new DialogInterface.OnClickListener() {
            public void onClick(DialogInterface dialog, int id) {
                // User has cancelled the dialog - do nothing
            }
        });

        return builder.create();
    }

    /**
     * Captures the Interface implementation
     * @param context The active context
     */
    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        try {
            this.distanceListener = (OnDistanceInputDoneListener)context;
        }
        catch (final ClassCastException e) {
            throw new ClassCastException(context.toString() + " must implement OnDistanceCompleteListener");
        }
    }

    /**
     * This listener is used to communicate with the LogFitbitActivity whenever the user chooses OK
     * in the dialog.
     */
    public  interface OnDistanceInputDoneListener {
        void onDone(String distance);
    }

    private OnDistanceInputDoneListener distanceListener;
}