package charistas.actibit;

import android.content.SharedPreferences;
import android.preference.CheckBoxPreference;
import android.preference.PreferenceFragment;
import android.preference.PreferenceScreen;
import android.support.v4.app.NavUtils;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

/**
 * This class is responsible for displaying and handling any changes in the Settings menu.
 */
public class SettingsActivity extends AppCompatActivity {
    static SharedPreferences.OnSharedPreferenceChangeListener listener;

    /**
     * Defines the UI of the SettingsActivity.
     * @param savedInstanceState The state generated by a previous instance of this activity
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_settings);

        getFragmentManager().beginTransaction().replace(android.R.id.content, new MyPreferenceFragment()).commit();
    }

    /**
     * If the user presses the Back button, he is navigated to PickActivity.
     */
    @Override
    public void onBackPressed() {
        NavUtils.navigateUpFromSameTask(this);
        super.onBackPressed();
    }

    /**
     * This class is responsible for creating the checkboxes in the Settings menu.
     */
    public static class MyPreferenceFragment extends PreferenceFragment implements SharedPreferences.OnSharedPreferenceChangeListener {

        @Override
        public void onCreate(final Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            addPreferencesFromResource(R.xml.preferences_general);

            listener = this;

            SharedPreferences prefs = getActivity().getSharedPreferences("charistas.actibit", MODE_PRIVATE);
            PreferenceScreen settings = getPreferenceScreen();
            CheckBoxPreference[] checkboxes = new CheckBoxPreference[FitbitActivity.getTotalActivities()];
            String [] activityNames = FitbitActivity.getActivityNames();
            for (int i = 0; i < FitbitActivity.getTotalActivities(); i++) {
                checkboxes[i] = new CheckBoxPreference(getActivity());
                checkboxes[i].setKey(activityNames[i]);
                checkboxes[i].setTitle(activityNames[i]);
                checkboxes[i].setChecked(prefs.getBoolean(activityNames[i], true));
                settings.addPreference(checkboxes[i]);
            }
        }

        /**
         * Register the appropriate listener every time the activity resumes.
         */
        @Override
        public void onResume() {
            super.onResume();
            getPreferenceScreen().getSharedPreferences().registerOnSharedPreferenceChangeListener(listener);
        }

        /**
         * Unregister the appropriate listener every time the activity is put on pause.
         */
        @Override
        public void onPause() {
            super.onPause();
            getPreferenceScreen().getSharedPreferences().unregisterOnSharedPreferenceChangeListener(listener);
        }

        /**
         * Whenever the user checks or un-checks a checkbox, we save it's current status for future
         * use.
         * @param sharedPreferences This is where we save the data
         * @param key This is a unique identifier that corresponds to the current checkbox
         */
        @Override
        public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, String key) {
            for (String activityName : FitbitActivity.getActivityNames()) {
                if (key.equals(activityName)) {
                    CheckBoxPreference checkbox = (CheckBoxPreference)findPreference(key);
                    SharedPreferences.Editor editor = getActivity().getSharedPreferences("charistas.actibit", MODE_PRIVATE).edit();
                    editor.putBoolean(key, checkbox.isChecked()).apply();
                }
            }
        }
    }
}
